# Site settings
title: Full Stack Story
email: matthewrudyjacobs+fullstackstory@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a narrated story of a few months of my life
  building a full-stack product from scratch
  and hoping to learn and teach at the same time
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fullstackstory.github.io/" # the base hostname & protocol for your site
twitter_username: matthewrudy
github_username:  fullstackstory

# Build settings
markdown: kramdown

permalink: none
